### ISSUE TITLE
Not work with Sonata Admin

### ISSUE THREAD

**Issue by sivinnguyen** [stfalcon/TinymceBundle#68]
I followed the instruction but it doesn't work

My configuration:

```
stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
```

My form builder

```
   protected function configureFormFields(FormMapper $formMapper)
       {
           $formMapper  
                    ->add('content', 'textarea', array(
                        'attr' => array(
                            'class' => 'tinymce',
                            'data-theme' => 'medium' // simple, advanced, bbcode
                           )
                    ))
            ;
      }
```

Nothing happen. Thanks!!!

**Comment by Entamut** [comment]
Hi,

This is just for those of you that landed here not knowing how to setup SonataAdmin and Tiny MCE (and don't want to spend time trying to make it work as I did ;) ).

I got it working (Symfony 4.2 + SonataAdmin Bundle 3.55.0 + stfalcon/tinymce-bundle 2.0.4) following these steps:

1. Assuming all Sonata stuff is ready and working:
```
composer require stfalcon/tinymce-bundle
```
2. Ensure one of your textarea fields is added to one of your forms in your admin controller (this is sonata related and you should already know where this goes ;) ):
```
// src/Admin/MyentityAdmin.php
protected function configureFormFields(FormMapper $formMapper)
{
  $formMapper->add('myTextArea', TextareaType::class, ['attr' => ['class' => 'tinymce']])
}
```
3.  Extend SonataAdmin edit template by creating a new template (path and name is up to you):
```
{# templates/Admin/CRUD/edit.html.twig #}
{% extends '@SonataAdmin/CRUD/edit.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {{ tinymce_init() }}
{% endblock %}
```
4. Tell SonataAdmin to use your extended template instead of default one:
```
# config/packages/sonata_admin.yaml
sonata_admin:
  templates:
    edit: 'Admin/CRUD/edit.html.twig'
```

Hope it works.

Other questions:
- Should I include the include_jquery and tinymce_jquery parameters? If you are loading jQuery already then I think you should.
- Where should I put the include_jquery and tinymce_jquery parameters? You can put those in services.yaml, but I think it would be better to have a separate file (i.e. stfalcon.yaml).

Cheers.
